#logging.level.org.springframework=DEBUG
spring.datasource.url= jdbc:postgresql://localhost:5432/market
spring.datasource.username= adminStar
spring.datasource.password= test
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update